version: 2.1

executors:
  node:
    docker:
      - image: node:16-slim
  python:
    docker:
      - image: python:3.9-bullseye

commands:
  install-latex-apt:
    steps:
      - run:
          name: Update package indexes
          command: apt-get -q update
      - run:
          name: Install LaTeX environment
          command: apt-get -q install -y texlive-latex-extra latexmk
  install-deps-python:
    steps:
      - run:
          name: Install python dependencies
          command: pip install sphinx sphinx-rtd-theme rstcheck pygments

jobs:
  lint_markdown:
    executor: node
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  check_rst:
    executor: python
    steps:
      - checkout
      - install-deps-python
      - run:
          name: Lint rst
          command: |
            rstcheck --report warning *.rst

  make_html:
    executor: python
    steps:
      - checkout
      - install-deps-python
      - run:
          name: make html
          command: |
            make html
      - store_artifacts:
          path: _build/html
          destination: html

  make_pdf_epub:
    executor: python
    steps:
      - checkout
      - install-deps-python
      - install-latex-apt
      - run:
          name: make pdf
          command: |
            make latexpdf
      - store_artifacts:
          path: _build/latex
          destination: pdf
      - run:
          name: make epub
          command: |
            make epub
      - store_artifacts:
          path: _build/epub
          destination: epub

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_markdown
      - check_rst
      - make_html:
          requires:
            - check_rst
      - make_pdf_epub:
          requires:
            - check_rst
